name: update-people

on:
  schedule:
    - cron: "0 12 1 * *"
  workflow_dispatch: {}

jobs:
  pydantic-people:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/people
        with:
          token: ${{ secrets.GH_C17_DEV_TOKEN }}
